"""empty message

Revision ID: effaef8bbbda
Revises: 9f31c06b1b74
Create Date: 2022-01-17 10:57:58.731389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effaef8bbbda'
down_revision = '9f31c06b1b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
